### ISSUE TITLE
Header menu confusing for slow internet.

### ISSUE THREAD

**Issue by rbakaou** [fullstackopen-2019/fullstackopen-2019.github.io#117]
Hello,
I just got a  little issue with the i18n of the header menu when i switch to English from the main page the content of the pages quickly loads the English version but the menu takes time to update due to my slow internet so when i click on the FAQ i get the FI version not the ENG one.

**Comment by marklaatikainen** [comment]
Header updates state after the page is loaded. Component's initial language is finnish. So this is why it behaves this way.
