### ISSUE TITLE
The link in the English General Info page goes to Finnish instructions

### ISSUE THREAD

**Issue by ljongkind** [fullstackopen-2019/fullstackopen-2019.github.io#118]
the link to the Git instructions refers to a page in Finnish.
it is line 145 of the code:
The course exercises are submitted to GitHub, so Git must be installed and one should know how to use it. Instructions for Git can be found i.a [here](https://github.com/mluukkai/ohjelmistotekniikka-kevat2019/blob/master/tehtavat/viikko1.md#gitin-alkeet).

**Comment by mluukkai** [comment]
Replaced with an English tutorial
