### ISSUE TITLE
Cannot hover or click on links through invisible header

### ISSUE THREAD

**Issue by gwpantazes** [fullstackopen-2019/fullstackopen-2019.github.io#160]
The header bar goes invisible when the user scrolls down, but captures pointer/touch events.

(Some of us like to read with the content right up against the top of the browser viewport 😛 )

Expected Behavior: The user would be able to click on a link right up against the top of the page if it is visible.

Observed Behavior: The user cannot click on a link that is beneath the invisible header.

Steps to Reproduce: 
1. Go to https://fullstackopen.com/en/part0/fundamentals_of_web_apps
2. Scroll down (causing the header to fade to invisible)
3. Scroll down until a link is right up against the top of the viewport
4. Attempt to hover or click on the link
5. Observe that even though the link is clearly visible, hovering and clicking on the link does not work.

Possible Fix: Would it be a simple fix to make the header pass on touch/pointer events while it's in its hidden state?

![Cannot click on link under the header](https://user-images.githubusercontent.com/797406/59114990-f6d14200-890d-11e9-9d64-bd3a8b66b167.png)

**Comment by alirezaghey** [comment]
I can confirm this.
