### ISSUE TITLE
1.10 : unicafe step5 exercise needs better explanation

### ISSUE THREAD

**Issue by prrdee** [fullstackopen-2019/fullstackopen-2019.github.io#362]
I can't figure it out what we're supposed to do here. Based on the image of the exercise instruction, I find it confusing.

**Comment by marcorichetta** [comment]
Hello.

Step 5 doesn't have image.

Step 4 image shows how statistics should be rendered when no feedback has been given.

**Comment by matnreyes** [comment]
I agree, I've no idea what the exercise is asking
