### ISSUE TITLE
npm run build:ui not working on Windows 10

### ISSUE THREAD

**Issue by Martialis39** [fullstackopen-2019/fullstackopen-2019.github.io#420]
As stated in the title, the `npm run build:ui` command does not work in Windows 10 CMD.

Propose adding reference to a Windows friendly command. In my experience, the following command works with the directory structure:
```
-- course
-- -- part 2 (frontend)
-- -- part 3 (backend)
```

`
"build:ui": "rmdir build /s /q && cd ../part2 && npm run build && xcopy build ..\\part3\\build /s /e /y /i",
`

**Comment by emindeniz99** [comment]
I had this issue, and I solved it via this code.
`
"build:ui": "(if exist build rmdir /s /q build )&& cd ../../part2/studying && npm run build --prod && xcopy /E build ..\\..\\part3\\studying\\build\\",
`
I have surfed on the internet, I could combine only this code. I couldn't find any alternative which works on Windows 10 1903.

**Comment by Kaltsoon** [comment]
Yes, Windows is a bit problematic and changing all the scripts to support it would simply be too much effort. That being said, we recommend using a virtualized Unix environment (e.g. docker or virtual machine) unless you want to figure out the windows specific commands yourselves.

**Comment by TheWildParamecium** [comment]
You can also avoid this problem by using git bash console (it is installed on windows when you install git). It uses the same Unix bash shell commands although being in windows, so you can keep then the same configuration of the tutorial in package.json

**Comment by I-keep-trying** [comment]
@TheWildParamecium Thank you, it works like a charm!

I did however, need to add the following to my Visual Studio Code settings:
`"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",`
but it's great because now I have a third option in the terminal selector, i.e., node, powershell, and now I have bash. 

I tested it with the build script and it worked! Yayy!!

**Comment by ShivS01** [comment]
> 
> 
> I had this issue, and I solved it via this code.
> `"build:ui": "(if exist build rmdir /s /q build )&& cd ../../part2/studying && npm run build --prod && xcopy /E build ..\\..\\part3\\studying\\build\\",`
> I have surfed on the internet, I could combine only this code. I couldn't find any alternative which works on Windows 10 1903.

Thanks, this works :)
