### ISSUE TITLE
Part 1c: Is lifting state up preferably to the App root component right?

### ISSUE THREAD

**Issue by grmano** [fullstackopen-2019/fullstackopen-2019.github.io#428]
On Part 1.c, topic [passing state to child components](https://fullstackopen.com/en/part1/component_state_event_handlers#passing-state-to-child-components), it is said that :

> One best practice in React is to lift the state up as high as possible in the component hierarchy, preferably to the App root component.

I think this my be misleading to many newcomers to React, it implies that the best place for all state to reside in on the App root component, which is not what the [reactjs docs](https://reactjs.org/docs/lifting-state-up.html) says about. It explicit says that state should be lifted to highest common ancestor to two components that use that state.

Recommending that state preferably resides on the App root would lead to many useless re-renders of components passing down prop changes to it's children and force many components to "know" about states that don't have anything to do with them.

I think it would be better to say that state should reside on the highest common ancestor and latter when a example with a deeper component tree is shown reintroduce the concept showing a refactor to highest common ancestor. (Similar to what is done on [reactjs documentation](https://reactjs.org/docs/lifting-state-up.html)

**Comment by mluukkai** [comment]
you're right about that. I'll clarify the text

**Comment by mluukkai** [comment]
fixed in 2020 edition
