### ISSUE TITLE
Tilallisen komponentin setTimeout-ongelma

### ISSUE THREAD

**Issue by petetnt** [fullstackopen-2019/fullstackopen-2019.github.io#43]
Ensinnäkin kiitos hienosta kurssista ja terveisiä CRA-tiimiltä 👋

Kävin omaksi iloksi kurssia lävitse ja huomasin seuraavan (todella yleisen) footgunin:

Kohdassa [Tilallinen komponentti](https://fullstackopen-2019.github.io/osa1/komponentin_tila_ja_tapahtumankasittely#tilallinen-komponentti) käytetään `setTimeout` metodia kutsumaan `setState` funktiota laskurin korottamiseksi:

```js
import React, { useState } from 'react'
import ReactDOM from 'react-dom'

const App = (props) => {
  const [ counter, setCounter ] = useState(0)

  setTimeout(
    () => setCounter(counter + 1),
    1000
  )

  return (
    <div>{counter}</div>
  )
}

ReactDOM.render(
  <App />, 
  document.getElementById('root')
)
```

Esimerkissä ei sinällään ole vikaa ja se toimii hyvin, mutta jos komponenttia muokataan _hieman_ tosi elämän usecasen suuntaan huomataan seuraava lifecycle-ongelma:

https://codesandbox.io/s/j28p3xz229

```js
import React, { useState } from 'react'
import ReactDOM from 'react-dom'

const Counter = (props) => {
  const [counter, setCounter] = useState(0)

  setTimeout(
    () => setCounter(counter + 1),
    100
  )

  return (
    <div>{counter}</div>
  )
}

function App() {
  const [x, set ] = useState(true)
  
  return <div onClick={() => set(false)}>
    {x ? <Counter /> : null}
  </div>
}

ReactDOM.render(
  <App />,
  document.getElementById('root')
)
```

Klikatessa laskuria silloin tällöin konsoliin nousee seuraava virheilmoitus:

> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

React poisti (unmount) `<Counter />` komponentin, mutta sitä vasten silti kutsuttiin `setState`a koska sitä ei ollut siistitty. setTimeoutin (kuten myös varsinkin `setIntervalin`) käyttö on harmittavan epätriviaalia, mutta laskurin siistiminen [`useEffect`](https://reactjs.org/docs/hooks-effect.html)-hookia käyttäen on mahdollista vaikkapa seuraavaan tyyliin:

https://codesandbox.io/s/j28p3xz229

```js
import React, { useState, useEffect } from 'react'
import ReactDOM from 'react-dom'

const Counter = (props) => {
  const [counter, setCounter] = useState(0)
  useEffect(() => {
    const x = setTimeout(
      () => setCounter(counter + 1),
      100
    )

    return () => clearTimeout(x)
  }, [counter])

  return (
    <div>{counter}</div>
  )
}

function App() {
  const [x, set ] = useState(true)
  
  return <div onClick={() => set(false)}>
    {x ? <Counter /> : null}
  </div>
}

ReactDOM.render(
  <App />,
  document.getElementById('root')
)
```

`useEffect`-hookia kutsutaan kun komponetti on mountattu ja siitä palautuvaa funktiota kun unmount-tapahtuu, joka korjaa ongelman. `useEffect`ille pitää kuitenkin syöttää muuttujan `counter` arvo arrayssä, jotta React uudelleen ajaa efektin kun arvo päivittyy.

Tuossa voisi olla hyvä sauma avata vähän Reactin lifecycleä, joka on olennainen osa (ja ehkä suurin päänvaiva) Reactia 😃 Samaa kaavaa käyttää myös Reactin [omat ohjeet](https://reactjs.org/docs/state-and-lifecycle.html)

**Comment by mluukkai** [comment]
Kiitokset! Tämä on tosi hyvä pointti ja pitänee nostaa esiin sopivassa kohtaa materiaalia. Itseasiassa tällä hetkellä effect-hookien käyttö on hieman ohkasta, ja tämä sopisi hyväksi motivoivaksi esimerkiksi.
