### ISSUE TITLE
Part 0: Requesting the favicon.ico throws error 404

### ISSUE THREAD

**Issue by LBeul** [fullstackopen-2019/fullstackopen-2019.github.io#485]
There seem to be issues with the favicon of [https://fullstack-exampleapp.herokuapp.com/notes](https://fullstack-exampleapp.herokuapp.com/notes) in the course's first section that could be confusing for beginners. Instead of just seeing the working requests that are described in the course module, they'll also receive an error 404. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37245841/65819157-b88fc380-e219-11e9-9026-8b70e7fae2bb.png">

**Comment by Kaltsoon** [comment]
Thanks for the feedback! That's true, perhaps we should add a favicon.
