### ISSUE TITLE
Part 1: Missing "Button" component in solutions

### ISSUE THREAD

**Issue by LBeul** [fullstackopen-2019/fullstackopen-2019.github.io#529]
In **Exercise 1.10: unicafe step5** it says 

> Extract the following two components:
> 
>     - Button for defining the buttons used for submitting feedback
>     - Statistic for displaying a single statistic, e.g. the average score.

The [solution of part 1](https://studies.cs.helsinki.fi/fullstackopen2019/#/solutions/1), however, doesn't include the _Button_ component and instead renders normal jsx buttons inside of the App component.

**Comment by mluukkai** [comment]
will be fixd in 2020 edition
