### ISSUE TITLE
Please explain noteService import in Notes Project

### ISSUE THREAD

**Issue by pythoncreate** [fullstackopen-2019/fullstackopen-2019.github.io#543]
On part 2 of the notes project, there is an import from the services file that looks like this:
`
import noteService from './services/notes'`

But there is no component or method in the notes file by this name.

Not sure if i'm totally missing something here, but could please explain why this is actually working?

**Comment by mluukkai** [comment]
if you use default export as follows:

```
export default { 
  getAll: getAll, 
  create: create, 
  update: update 
}
```
you are exporting an object that has three fields.

You van import the whole object to be referrend with name noteService as follows:

import noteService from './services/notes'

You can give it any name, eg doing

import noteService from './services/notes'

would refer the exported object with x
