### ISSUE TITLE
Part 3c -> put request for updating a note -> note vs new Note

### ISSUE THREAD

**Issue by Akrabut** [fullstackopen-2019/fullstackopen-2019.github.io#558]
This took my a while to figure out (Googling also didn't help much) - the reasoning behind creating a note object rather than using a model constructor.

I suggest mentioning that using the Note model constructor initiates it with an `_id` key, so that when attempting to update Mongo will be pissed and throw an error.

Great course by the way!

**Comment by Kaltsoon** [comment]
Thanks for the feedback! Could you be more specific about which part of the material you are talking about? Some code samples of "creating a note object" and "using a model constructor" would be helpful.

> I suggest mentioning that using the Note model constructor initiates it with an _id key, so that when attempting to update Mongo will be pissed and throw an error.

Actually the `_id` key set by the mongodb database outside your application unless you have set it by yourself: https://docs.mongodb.com/manual/reference/method/db.collection.insert/#id-field

**Comment by Akrabut** [comment]
I'm talking about the difference between 
```
User.create({
      name: req.body.name,
      email: req.body.email,
      password: passwordHash,
    })
```
Where we call the create method on the model with a given JS object.
An error I have trouble figuring was using
```
const user = new User({ same args })
User.create(user) // generates an error because the user object already has an _id attribute.
```
Was thinking you might want to mention it to help students avoid confusion :]

**Comment by Kaltsoon** [comment]
Okay, now I got it, thanks for clarifying! We will consider adding some additional information about this. :)
