### ISSUE TITLE
Part 6b - Switch from "connect", "mapStateToProps",  and "mapDispatchToProps" methods to useSelector() and useDispatch()

### ISSUE THREAD

**Issue by reggievick** [fullstackopen-2019/fullstackopen-2019.github.io#560]
With the introduction of hooks, i find it much easier to use the new "useSelector()" and "useDispatch()" methods to create redux actions and access the redux state.  Since the course uses functional components and hooks over the traditional class component, I think using the new redux hooks would fall right inline with the curriculum.

For example, to access notes in the redux state:
```js
import React from 'react'
import { useSelector } from 'react-redux'

export const NotesComponent = () => {
  const notes = useSelector(state => state.notes)
  return <div>{notes}</div>
}
```

[Redux Hooks](https://react-redux.js.org/next/api/hooks)

**Comment by mluukkai** [comment]
will be changed in 2020 edition
