### ISSUE TITLE
MERN seems deprecated

### ISSUE THREAD

**Issue by pihvi** [fullstackopen-2019/fullstackopen-2019.github.io#569]
https://github.com/fullstackopen-2019/fullstackopen-2019.github.io/blame/source/src/content/7/fi/osa7e.md#L23

<img width="635" alt="image" src="https://user-images.githubusercontent.com/72422/68070729-b2da5000-fd7a-11e9-9adc-8fa4de127bca.png">

Also mern.io is not responding at the moment..

**Comment by mluukkai** [comment]
will be removed from 2020 edition
