### ISSUE TITLE
Eject link -> 404

### ISSUE THREAD

**Issue by pihvi** [fullstackopen-2019/fullstackopen-2019.github.io#570]
https://github.com/fullstackopen-2019/fullstackopen-2019.github.io/blame/6420dd39621ccfaa9603e64e03d307d71d7f77a7/src/content/7/fi/osa7c.md#L874

links to https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-eject that is no more

**Comment by Kaltsoon** [comment]
Thanks, we'll fix this in the next version of the material.
