### ISSUE TITLE
Something is missing in the instructions for anecdotes [step 2 and 3]

### ISSUE THREAD

**Issue by tabasco-addict** [fullstackopen-2019/fullstackopen-2019.github.io#606]
I think useState for complex data structures is not being explained adequately. There needs to be multiple values in the state to store votes for each anecdote, but the starter code only shows a single vote and setVote. It isn't clear how to set up state as an object that can handle this.

> " _if you decide_ to store the votes of each anecdote into an array or object in the component's state, you should refer to the material to see the correct way of updating state stored in complex data structures like objects and arrays."

The emphasized phrasing here tells us there is a way to do this without storing an object or array in the state. But this not clear.

The example code in the Complex State section doesn't really help, since 

> "Storing all of the state in a single state object is a bad choice for this particular application; there's no apparent benefit and the resulting application is a lot more complex". 

The example in the Handling Arrays section is also not really applicable to the exercise. It shows how to have an array that can accept two different values, but each value needs its own function. I'm assuming that creating a function for each anecdote would not be optimal, but that's the only solution that the readers are led to from the guide.

I think kicking the user to the React docs to figure this out defeats the purpose of having a course. Please let me know if there are any revisions to this section in progress. Thanks.

**Comment by mluukkai** [comment]
Will be clarified a bit in 2020 edition. Since this is a starred exercise it will be a bit harder than the previous ones so direct hints will not be given anyway
