### ISSUE TITLE
Minor spelling mistake on the English version of the FAQ page

### ISSUE THREAD

**Issue by ChangoFoster** [fullstackopen-2019/fullstackopen-2019.github.io#658]
There are a couple of spelling mistakes on this page: https://fullstackopen.com/en/faq

gereatest -> greatest
cypres.io -> cypress.io
see more here -> Add "/en/" to the link

Resolved by #659

**Comment by Kaltsoon** [comment]
Thanks, these issues have been fixed in the next version of the material
